export interface QuizQuestion {
  q: string;
  options: string[];
  answer: number;
  category: string;
}

export const QUIZ_QUESTIONS: QuizQuestion[] = [
  // ── Old Testament ──────────────────────────────────────────
  {
    q: "Who built the ark?",
    options: ["Moses", "Noah", "Abraham", "David"],
    answer: 1,
    category: "Old Testament",
  },
  {
    q: "Who was the first man according to the Bible?",
    options: ["Cain", "Abel", "Noah", "Adam"],
    answer: 3,
    category: "Old Testament",
  },
  {
    q: "How many days did creation take?",
    options: ["5", "6", "7", "8"],
    answer: 1,
    category: "Old Testament",
  },
  {
    q: "Who wrote most of the Psalms?",
    options: ["Solomon", "Moses", "David", "Isaiah"],
    answer: 2,
    category: "Old Testament",
  },
  {
    q: "How many plagues hit Egypt?",
    options: ["7", "8", "9", "10"],
    answer: 3,
    category: "Old Testament",
  },
  {
    q: "Who was the wisest king in the Bible?",
    options: ["David", "Saul", "Solomon", "Hezekiah"],
    answer: 2,
    category: "Old Testament",
  },
  {
    q: "Who was thrown into the lions den?",
    options: ["Shadrach", "Daniel", "Elijah", "Ezekiel"],
    answer: 1,
    category: "Old Testament",
  },
  {
    q: "What did God create on the first day?",
    options: ["Animals", "Plants", "Light", "Stars"],
    answer: 2,
    category: "Old Testament",
  },
  {
    q: "What was Moses' brother's name?",
    options: ["Aaron", "Caleb", "Joshua", "Eli"],
    answer: 0,
    category: "Old Testament",
  },
  {
    q: "Who was swallowed by a great fish?",
    options: ["Elijah", "Isaiah", "Jonah", "Ezekiel"],
    answer: 2,
    category: "Old Testament",
  },
  {
    q: "Who slew Goliath?",
    options: ["Saul", "Jonathan", "David", "Samuel"],
    answer: 2,
    category: "Old Testament",
  },
  {
    q: "What was the name of Abraham's wife?",
    options: ["Rachel", "Leah", "Sarah", "Rebekah"],
    answer: 2,
    category: "Old Testament",
  },
  {
    q: "How many sons did Jacob have?",
    options: ["10", "11", "12", "13"],
    answer: 2,
    category: "Old Testament",
  },
  {
    q: "Who was sold into slavery by his brothers?",
    options: ["Benjamin", "Joseph", "Reuben", "Judah"],
    answer: 1,
    category: "Old Testament",
  },
  {
    q: "What did Samson's strength depend on?",
    options: ["His belt", "His staff", "His hair", "His shield"],
    answer: 2,
    category: "Old Testament",
  },
  {
    q: "Who was the first king of Israel?",
    options: ["David", "Solomon", "Saul", "Samuel"],
    answer: 2,
    category: "Old Testament",
  },
  {
    q: "Which mountain did Moses receive the Ten Commandments on?",
    options: ["Mount Zion", "Mount Carmel", "Mount Sinai", "Mount Horeb"],
    answer: 2,
    category: "Old Testament",
  },
  {
    q: "What was the name of Moses' successor?",
    options: ["Caleb", "Joshua", "Eleazar", "Phinehas"],
    answer: 1,
    category: "Old Testament",
  },
  {
    q: "Who was the mother of Samuel?",
    options: ["Deborah", "Hannah", "Ruth", "Naomi"],
    answer: 1,
    category: "Old Testament",
  },
  {
    q: "What city did Jonah refuse to go to?",
    options: ["Babylon", "Jerusalem", "Nineveh", "Tyre"],
    answer: 2,
    category: "Old Testament",
  },
  {
    q: "Who was the father of John the Baptist?",
    options: ["Simeon", "Zechariah", "Joseph", "Eli"],
    answer: 1,
    category: "Old Testament",
  },
  {
    q: "How many years did the Israelites wander in the wilderness?",
    options: ["20", "30", "40", "50"],
    answer: 2,
    category: "Old Testament",
  },
  {
    q: "What was Elijah taken up to heaven in?",
    options: ["A cloud", "A chariot of fire", "A whirlwind", "Both B and C"],
    answer: 3,
    category: "Old Testament",
  },
  {
    q: "Who was Ruth's mother-in-law?",
    options: ["Orpah", "Hannah", "Naomi", "Miriam"],
    answer: 2,
    category: "Old Testament",
  },
  {
    q: "What was the name of the garden where Adam and Eve lived?",
    options: [
      "Garden of Gethsemane",
      "Garden of Eden",
      "Garden of Olives",
      "Garden of Sinai",
    ],
    answer: 1,
    category: "Old Testament",
  },
  {
    q: "Who interpreted Pharaoh's dreams?",
    options: ["Moses", "Aaron", "Joseph", "Daniel"],
    answer: 2,
    category: "Old Testament",
  },
  {
    q: "What weapon did David use to defeat Goliath?",
    options: ["Sword", "Spear", "Sling and stone", "Arrow"],
    answer: 2,
    category: "Old Testament",
  },
  {
    q: "Which prophet was taken to heaven without dying?",
    options: ["Elisha", "Elijah", "Isaiah", "Enoch"],
    answer: 1,
    category: "Old Testament",
  },
  {
    q: "What was built to reach the heavens in Genesis?",
    options: [
      "The Temple",
      "The Tower of Babel",
      "Noah's Ark",
      "The Tabernacle",
    ],
    answer: 1,
    category: "Old Testament",
  },
  {
    q: "Who was the commander of Israel's army under David?",
    options: ["Joab", "Abner", "Uriah", "Benaiah"],
    answer: 0,
    category: "Old Testament",
  },
  {
    q: "How many days and nights did it rain during the flood?",
    options: ["20", "30", "40", "50"],
    answer: 2,
    category: "Old Testament",
  },
  {
    q: "Who anointed David as king?",
    options: ["Moses", "Eli", "Nathan", "Samuel"],
    answer: 3,
    category: "Old Testament",
  },
  {
    q: "What were the three Hebrews thrown into for refusing to bow?",
    options: ["A pit", "The sea", "A fiery furnace", "The lions den"],
    answer: 2,
    category: "Old Testament",
  },
  {
    q: "Who was the first judge of Israel?",
    options: ["Gideon", "Samson", "Othniel", "Deborah"],
    answer: 2,
    category: "Old Testament",
  },
  {
    q: "Which book comes right after Genesis?",
    options: ["Leviticus", "Numbers", "Exodus", "Deuteronomy"],
    answer: 2,
    category: "Old Testament",
  },

  // ── New Testament ──────────────────────────────────────────
  {
    q: "How many disciples did Jesus have?",
    options: ["10", "11", "12", "13"],
    answer: 2,
    category: "New Testament",
  },
  {
    q: "Where was Jesus born?",
    options: ["Jerusalem", "Nazareth", "Bethlehem", "Jericho"],
    answer: 2,
    category: "New Testament",
  },
  {
    q: "What river was Jesus baptized in?",
    options: ["Nile", "Euphrates", "Jordan", "Galilee"],
    answer: 2,
    category: "New Testament",
  },
  {
    q: "What did Jesus turn water into?",
    options: ["Milk", "Wine", "Juice", "Oil"],
    answer: 1,
    category: "New Testament",
  },
  {
    q: "Who betrayed Jesus?",
    options: ["Peter", "Thomas", "John", "Judas"],
    answer: 3,
    category: "New Testament",
  },
  {
    q: "How many days was Jesus in the wilderness?",
    options: ["30", "40", "50", "60"],
    answer: 1,
    category: "New Testament",
  },
  {
    q: "Who denied Jesus three times?",
    options: ["John", "James", "Peter", "Andrew"],
    answer: 2,
    category: "New Testament",
  },
  {
    q: "Who was the mother of Jesus?",
    options: ["Martha", "Mary", "Elizabeth", "Sarah"],
    answer: 1,
    category: "New Testament",
  },
  {
    q: "Which disciple walked on water with Jesus?",
    options: ["John", "James", "Andrew", "Peter"],
    answer: 3,
    category: "New Testament",
  },
  {
    q: "What is the shortest verse in the Bible?",
    options: ["God wept.", "Fear not.", "Jesus wept.", "Rejoice always."],
    answer: 2,
    category: "New Testament",
  },
  {
    q: "Who baptized Jesus?",
    options: ["Peter", "John the Baptist", "Andrew", "Philip"],
    answer: 1,
    category: "New Testament",
  },
  {
    q: "What did Jesus feed 5000 people with?",
    options: [
      "Bread and meat",
      "Fish and fruit",
      "5 loaves and 2 fish",
      "7 loaves and 3 fish",
    ],
    answer: 2,
    category: "New Testament",
  },
  {
    q: "Who was the first disciple Jesus called?",
    options: ["John", "Andrew", "Simon Peter", "Philip"],
    answer: 2,
    category: "New Testament",
  },
  {
    q: "On which day did Jesus rise from the dead?",
    options: ["First", "Second", "Third", "Fourth"],
    answer: 2,
    category: "New Testament",
  },
  {
    q: "What was the name of the tax collector Jesus called as a disciple?",
    options: ["Zacchaeus", "Matthew", "Luke", "Bartimaeus"],
    answer: 1,
    category: "New Testament",
  },
  {
    q: "Where did Jesus perform his first miracle?",
    options: ["Jerusalem", "Capernaum", "Cana", "Nazareth"],
    answer: 2,
    category: "New Testament",
  },
  {
    q: "Who asked Pilate for Jesus body after the crucifixion?",
    options: ["Nicodemus", "John", "Joseph of Arimathea", "Mary Magdalene"],
    answer: 2,
    category: "New Testament",
  },
  {
    q: "What was written on the sign above Jesus on the cross?",
    options: [
      "King of the Jews",
      "Son of God",
      "Saviour of the World",
      "King of Israel",
    ],
    answer: 0,
    category: "New Testament",
  },
  {
    q: "Who was the first person to see Jesus after the resurrection?",
    options: ["Peter", "John", "Mary Magdalene", "Mary his mother"],
    answer: 2,
    category: "New Testament",
  },
  {
    q: "Which disciple doubted the resurrection until he saw Jesus?",
    options: ["Philip", "Nathanael", "Thomas", "Bartholomew"],
    answer: 2,
    category: "New Testament",
  },
  {
    q: "What was Paul's name before his conversion?",
    options: ["Barnabas", "Silas", "Saul", "Titus"],
    answer: 2,
    category: "New Testament",
  },
  {
    q: "Who was struck blind on the road to Damascus?",
    options: ["Barnabas", "Stephen", "Paul", "Silas"],
    answer: 2,
    category: "New Testament",
  },
  {
    q: "What was the name of the disciple who replaced Judas?",
    options: ["Barnabas", "Matthias", "Joseph", "Silas"],
    answer: 1,
    category: "New Testament",
  },
  {
    q: "How many people were baptized on the day of Pentecost?",
    options: ["1000", "2000", "3000", "5000"],
    answer: 2,
    category: "New Testament",
  },
  {
    q: "Who was the first Christian martyr?",
    options: ["James", "Peter", "Stephen", "Philip"],
    answer: 2,
    category: "New Testament",
  },
  {
    q: "Which Roman governor handed Jesus over to be crucified?",
    options: ["Herod", "Caesar", "Pontius Pilate", "Felix"],
    answer: 2,
    category: "New Testament",
  },
  {
    q: "What was the name of the blind man Jesus healed near Jericho?",
    options: ["Lazarus", "Bartimaeus", "Simon", "Malchus"],
    answer: 1,
    category: "New Testament",
  },
  {
    q: "How many loaves did Jesus use to feed the 4000?",
    options: ["5", "6", "7", "8"],
    answer: 2,
    category: "New Testament",
  },
  {
    q: "Who helped Jesus carry the cross?",
    options: ["John", "Simon of Cyrene", "Joseph", "Nicodemus"],
    answer: 1,
    category: "New Testament",
  },
  {
    q: "What was the name of the pool where Jesus healed a paralysed man?",
    options: [
      "Pool of Siloam",
      "Pool of Bethesda",
      "Pool of Gibeon",
      "Pool of Solomon",
    ],
    answer: 1,
    category: "New Testament",
  },
  {
    q: "Which apostle wrote the most books in the New Testament?",
    options: ["John", "Peter", "James", "Paul"],
    answer: 3,
    category: "New Testament",
  },

  // ── Books & Facts ──────────────────────────────────────────
  {
    q: "What is the first book of the Bible?",
    options: ["Exodus", "Genesis", "Psalms", "Matthew"],
    answer: 1,
    category: "Books",
  },
  {
    q: "Who wrote the book of Revelation?",
    options: ["Paul", "Peter", "John", "James"],
    answer: 2,
    category: "Books",
  },
  {
    q: "How many books are in the New Testament?",
    options: ["25", "26", "27", "28"],
    answer: 2,
    category: "Books",
  },
  {
    q: "How many books are in the entire Bible?",
    options: ["60", "64", "66", "68"],
    answer: 2,
    category: "Books",
  },
  {
    q: "What is the last book of the Old Testament?",
    options: ["Zechariah", "Malachi", "Haggai", "Zephaniah"],
    answer: 1,
    category: "Books",
  },
  {
    q: "What is the last book of the Bible?",
    options: ["Jude", "3 John", "Revelation", "Hebrews"],
    answer: 2,
    category: "Books",
  },
  {
    q: "How many books are in the Old Testament?",
    options: ["37", "39", "41", "43"],
    answer: 1,
    category: "Books",
  },
  {
    q: "Which is the longest book in the Bible?",
    options: ["Isaiah", "Jeremiah", "Psalms", "Ezekiel"],
    answer: 2,
    category: "Books",
  },
  {
    q: "Which is the shortest book in the Bible?",
    options: ["2 John", "3 John", "Obadiah", "Philemon"],
    answer: 1,
    category: "Books",
  },
  {
    q: "Which book contains the Ten Commandments?",
    options: ["Genesis", "Leviticus", "Exodus", "Numbers"],
    answer: 2,
    category: "Books",
  },
  {
    q: "What is the middle book of the Bible?",
    options: ["Psalms", "Proverbs", "Micah", "Job"],
    answer: 0,
    category: "Books",
  },
  {
    q: "Who wrote the book of Acts?",
    options: ["Paul", "Mark", "Luke", "John"],
    answer: 2,
    category: "Books",
  },
  {
    q: "How many chapters are in the book of Psalms?",
    options: ["100", "120", "150", "180"],
    answer: 2,
    category: "Books",
  },
  {
    q: "Which book of the Bible never mentions the name of God?",
    options: ["Song of Solomon", "Ruth", "Esther", "Both A and C"],
    answer: 3,
    category: "Books",
  },
  {
    q: "Who wrote the Gospel of Luke?",
    options: [
      "Luke the apostle",
      "Luke the physician",
      "Luke the prophet",
      "Luke the scribe",
    ],
    answer: 1,
    category: "Books",
  },
  {
    q: "Which Gospel was written first?",
    options: ["Matthew", "Mark", "Luke", "John"],
    answer: 1,
    category: "Books",
  },
  {
    q: "How many letters did Paul write in the New Testament?",
    options: ["11", "12", "13", "14"],
    answer: 2,
    category: "Books",
  },
  {
    q: "Which book comes right after the four Gospels?",
    options: ["Romans", "Acts", "Hebrews", "1 Corinthians"],
    answer: 1,
    category: "Books",
  },
  {
    q: "What language was most of the Old Testament originally written in?",
    options: ["Greek", "Latin", "Aramaic", "Hebrew"],
    answer: 3,
    category: "Books",
  },
  {
    q: "What language was the New Testament originally written in?",
    options: ["Latin", "Hebrew", "Greek", "Aramaic"],
    answer: 2,
    category: "Books",
  },
  {
    q: "Which book records the history of the early church?",
    options: ["Romans", "Hebrews", "Acts", "Galatians"],
    answer: 2,
    category: "Books",
  },
  {
    q: "How many Psalms are attributed to David?",
    options: ["53", "63", "73", "83"],
    answer: 2,
    category: "Books",
  },
  {
    q: "Which book of the Bible contains the Sermon on the Mount?",
    options: ["Mark", "Luke", "John", "Matthew"],
    answer: 3,
    category: "Books",
  },
  {
    q: "Which Old Testament book tells the story of a woman who became queen of Persia?",
    options: ["Ruth", "Judith", "Esther", "Naomi"],
    answer: 2,
    category: "Books",
  },
  {
    q: "How many chapters does the book of Revelation have?",
    options: ["20", "22", "24", "26"],
    answer: 1,
    category: "Books",
  },
  {
    q: "Which book comes first in the New Testament?",
    options: ["Mark", "Luke", "John", "Matthew"],
    answer: 3,
    category: "Books",
  },
];
