// All scriptures, static TS file
export const verses = [];
export interface Verse {
  book: string;
  chapter: number;
  verse: number;
  text: string;
}

export const BOOKS = [
  "Genesis",
  "Exodus",
  "Psalms",
  "Proverbs",
  "Isaiah",
  "Jeremiah",
  "Matthew",
  "Mark",
  "Luke",
  "John",
  "Acts",
  "Romans",
  "1 Corinthians",
  "2 Corinthians",
  "Galatians",
  "Ephesians",
  "Philippians",
  "Colossians",
  "1 Thessalonians",
  "1 Timothy",
  "2 Timothy",
  "Hebrews",
  "James",
  "1 Peter",
  "Revelation",
];

export const VERSES: Verse[] = [
  {
    book: "John",
    chapter: 3,
    verse: 16,
    text: "For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life.",
  },
  {
    book: "John",
    chapter: 3,
    verse: 17,
    text: "For God did not send his Son into the world to condemn the world, but to save the world through him.",
  },
  {
    book: "John",
    chapter: 14,
    verse: 6,
    text: "Jesus answered, I am the way and the truth and the life. No one comes to the Father except through me.",
  },
  {
    book: "John",
    chapter: 14,
    verse: 27,
    text: "Peace I leave with you; my peace I give you. I do not give to you as the world gives. Do not let your hearts be troubled and do not be afraid.",
  },
  {
    book: "Psalms",
    chapter: 23,
    verse: 1,
    text: "The LORD is my shepherd, I lack nothing.",
  },
  {
    book: "Psalms",
    chapter: 23,
    verse: 2,
    text: "He makes me lie down in green pastures, he leads me beside quiet waters.",
  },
  {
    book: "Psalms",
    chapter: 23,
    verse: 3,
    text: "He refreshes my soul. He guides me along the right paths for his name's sake.",
  },
  {
    book: "Psalms",
    chapter: 23,
    verse: 4,
    text: "Even though I walk through the darkest valley, I will fear no evil, for you are with me; your rod and your staff, they comfort me.",
  },
  {
    book: "Psalms",
    chapter: 119,
    verse: 105,
    text: "Your word is a lamp for my feet, a light on my path.",
  },
  {
    book: "Psalms",
    chapter: 46,
    verse: 1,
    text: "God is our refuge and strength, an ever-present help in trouble.",
  },
  {
    book: "Psalms",
    chapter: 27,
    verse: 1,
    text: "The LORD is my light and my salvation — whom shall I fear? The LORD is the stronghold of my life — of whom shall I be afraid?",
  },
  {
    book: "Proverbs",
    chapter: 3,
    verse: 5,
    text: "Trust in the LORD with all your heart and lean not on your own understanding.",
  },
  {
    book: "Proverbs",
    chapter: 3,
    verse: 6,
    text: "In all your ways submit to him, and he will make your paths straight.",
  },
  {
    book: "Proverbs",
    chapter: 4,
    verse: 23,
    text: "Above all else, guard your heart, for everything you do flows from it.",
  },
  {
    book: "Isaiah",
    chapter: 40,
    verse: 31,
    text: "But those who hope in the LORD will renew their strength. They will soar on wings like eagles; they will run and not grow weary, they will walk and not be faint.",
  },
  {
    book: "Isaiah",
    chapter: 41,
    verse: 10,
    text: "So do not fear, for I am with you; do not be dismayed, for I am your God. I will strengthen you and help you; I will uphold you with my righteous right hand.",
  },
  {
    book: "Jeremiah",
    chapter: 29,
    verse: 11,
    text: "For I know the plans I have for you, declares the LORD, plans to prosper you and not to harm you, plans to give you hope and a future.",
  },
  {
    book: "Matthew",
    chapter: 5,
    verse: 3,
    text: "Blessed are the poor in spirit, for theirs is the kingdom of heaven.",
  },
  {
    book: "Matthew",
    chapter: 5,
    verse: 4,
    text: "Blessed are those who mourn, for they will be comforted.",
  },
  {
    book: "Matthew",
    chapter: 5,
    verse: 5,
    text: "Blessed are the meek, for they will inherit the earth.",
  },
  {
    book: "Matthew",
    chapter: 6,
    verse: 33,
    text: "But seek first his kingdom and his righteousness, and all these things will be given to you as well.",
  },
  {
    book: "Matthew",
    chapter: 11,
    verse: 28,
    text: "Come to me, all you who are weary and burdened, and I will give you rest.",
  },
  {
    book: "Romans",
    chapter: 8,
    verse: 28,
    text: "And we know that in all things God works for the good of those who love him, who have been called according to his purpose.",
  },
  {
    book: "Romans",
    chapter: 8,
    verse: 38,
    text: "For I am convinced that neither death nor life, neither angels nor demons, neither the present nor the future, nor any powers, neither height nor depth, nor anything else in all creation, will be able to separate us from the love of God.",
  },
  {
    book: "Romans",
    chapter: 12,
    verse: 2,
    text: "Do not conform to the pattern of this world, but be transformed by the renewing of your mind.",
  },
  {
    book: "Philippians",
    chapter: 4,
    verse: 6,
    text: "Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God.",
  },
  {
    book: "Philippians",
    chapter: 4,
    verse: 7,
    text: "And the peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus.",
  },
  {
    book: "Philippians",
    chapter: 4,
    verse: 13,
    text: "I can do all this through him who gives me strength.",
  },
  {
    book: "Ephesians",
    chapter: 2,
    verse: 8,
    text: "For it is by grace you have been saved, through faith — and this is not from yourselves, it is the gift of God.",
  },
  {
    book: "Ephesians",
    chapter: 6,
    verse: 11,
    text: "Put on the full armor of God, so that you can take your stand against the devil's schemes.",
  },
  {
    book: "Hebrews",
    chapter: 11,
    verse: 1,
    text: "Now faith is confidence in what we hope for and assurance about what we do not see.",
  },
  {
    book: "James",
    chapter: 1,
    verse: 2,
    text: "Consider it pure joy, my brothers and sisters, whenever you face trials of many kinds.",
  },
  {
    book: "James",
    chapter: 1,
    verse: 17,
    text: "Every good and perfect gift is from above, coming down from the Father of the heavenly lights, who does not change like shifting shadows.",
  },
  {
    book: "1 Peter",
    chapter: 5,
    verse: 7,
    text: "Cast all your anxiety on him because he cares for you.",
  },
  {
    book: "Revelation",
    chapter: 21,
    verse: 4,
    text: "He will wipe every tear from their eyes. There will be no more death or mourning or crying or pain, for the old order of things has passed away.",
  },
  {
    book: "Genesis",
    chapter: 1,
    verse: 1,
    text: "In the beginning God created the heavens and the earth.",
  },
  {
    book: "Genesis",
    chapter: 1,
    verse: 27,
    text: "So God created mankind in his own image, in the image of God he created them; male and female he created them.",
  },
  {
    book: "Acts",
    chapter: 1,
    verse: 8,
    text: "But you will receive power when the Holy Spirit comes on you; and you will be my witnesses in Jerusalem, and in all Judea and Samaria, and to the ends of the earth.",
  },
  {
    book: "2 Timothy",
    chapter: 3,
    verse: 16,
    text: "All Scripture is God-breathed and is useful for teaching, rebuking, correcting and training in righteousness.",
  },
  {
    book: "1 Corinthians",
    chapter: 13,
    verse: 4,
    text: "Love is patient, love is kind. It does not envy, it does not boast, it is not proud.",
  },
  {
    book: "1 Corinthians",
    chapter: 13,
    verse: 13,
    text: "And now these three remain: faith, hope and love. But the greatest of these is love.",
  },
  {
    book: "Galatians",
    chapter: 5,
    verse: 22,
    text: "But the fruit of the Spirit is love, joy, peace, forbearance, kindness, goodness, faithfulness, gentleness and self-control.",
  },
  {
    book: "Colossians",
    chapter: 3,
    verse: 17,
    text: "And whatever you do, whether in word or deed, do it all in the name of the Lord Jesus, giving thanks to God the Father through him.",
  },
];
